name: final_project_doa
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  android_intent_plus: ^6.0.0
  firebase_auth: ^6.1.0
  firebase_core: ^4.1.1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_local_notifications: ^19.4.2
  flutter_social_button: ^1.1.6+1
  flutter_timezone: ^4.1.1
  image_picker: ^1.2.0
  onboarding: ^4.0.2
  path_provider: ^2.1.5
  shared_preferences: ^2.5.3
  social_login_buttons: ^1.0.7
  timezone: ^0.10.1
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
